### ISSUE TITLE
No grills found

### ISSUE THREAD

**Issue by hoopsta1423** [dknowles2/ha-pitboss#12]
## System Information

version | core-2023.6.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4855
Installed Version | 1.32.1
Stage | running
Available Repositories | 1287
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 15, 2023 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 13.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | NGINX Home Assistant SSL proxy (3.5.0), Duck DNS (1.15.0), Samba share (10.0.2), Terminal & SSH (9.7.1), File editor (5.6.0), AdGuard Home (4.8.8), Mosquitto broker (6.2.1), Nginx Proxy Manager (0.12.3), Network UPS Tools (0.11.2), ESPHome (2022.3.1), MariaDB (2.6.1), Node-RED (14.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 12
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 5, 2023 at 10:45 PM
-- | --
current_recorder_run | June 9, 2023 at 11:01 AM
estimated_db_size | 332.73 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Just set up my PB850PS2 grill and connected to my wifi network. I have a fixed IP for the grill through my router. Installed ha-pitboss through HACS but when trying to add the integration I get an error "no grills found"

Is there a way to manually input the IP of the grill?

![image](https://github.com/dknowles2/ha-pitboss/assets/44473565/752fa56c-d5dd-49c0-9882-df3581513d97)

### Reproduction steps

1.install ha-pitboss via custom repository in HACS
2.add integration
3.no grills found
...

### Debug logs

```text
no errors in log
```

**Comment by hoopsta1423** [comment]
Just noticed it used BLE only - not wifi. my mistake!

**Comment by dknowles2** [comment]
Yep. BLE only. On my grill there's no local access over WiFi. It's only used for uploading state to the cloud as far as I can tell.

**Comment by hoopsta1423** [comment]
Yup, my bad! I got it setup via bluetooth on a fresh HA docker instance but am seeing errors. Made another thread [Here](https://github.com/dknowles2/ha-pitboss/issues/13)
