### ISSUE TITLE
Error Sensors?

### ISSUE THREAD

**Issue by jacobwtyler** [dknowles2/ha-pitboss#23]
### System Health details

Error 1

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Home Assistant is recognizing my grill but I’m getting an ErP error on the grill and Home Assistant is showing error 1 sensor ad problem detected and all others as OK. I was hoping to use the Home Assistant integration to sort of troubleshoot what was going on with the grill but I was wondering if you knew what the error 1, error 2 and error 3 sensors represent. Many thanks. 

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Error 1
```

**Comment by dknowles2** [comment]
Unfortunately I don't know what the different error codes mean.

**Comment by dknowles2** [comment]
I realized there's a hint in the product manual. `ErP` is an error with a temperature probe. I'd be willing to bet that errors 1, 2, and 3 correspond to the probe number that has the error. (And 3 is actually unused since there's not a 3rd probe port)
