### ISSUE TITLE
Call service failure

### ISSUE THREAD

**Issue by rossman-home** [dknowles2/ha-pitboss#3]
## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1246
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 20, 2023 at 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 30.8 GB
disk_used | 9.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.110.3), Terminal & SSH (9.6.1), File editor (5.5.0), Google Assistant SDK (2.5.0), NGINX Home Assistant SSL proxy (3.2.0), Simple Scheduler (2.1), Samba share (10.0.0), Mosquitto broker (6.2.0), Zigbee2MQTT (1.30.3-1), Cloudflared (4.0.14), Studio Code Server (5.5.6), Grafana (8.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 19
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 23, 2023 at 8:29 AM
-- | --
current_recorder_run | April 1, 2023 at 5:21 PM
estimated_db_size | 105.80 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Getting an error for "Failed to call service switch/turn_on.  'BlueprintDataUpdateCoordinator' object has no attribute 'api' when attempting to flip switch.integration_switch  Also noticing sensor.integration_sensor has the following in it "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto"  Not sure if it is related.

### Reproduction steps

I copied all files over to a new folder in custom_components, added the integration and typed in my username and password for Pitboss.  I tried to flip the integration switch and received the error

### Debug logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/pitboss/switch.py:54
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:16:16 AM (7 occurrences)
Last logged: 10:55:36 AM

[140501655326000] 'BlueprintDataUpdateCoordinator' object has no attribute 'api'
[140501624798704] 'BlueprintDataUpdateCoordinator' object has no attribute 'api'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/pitboss/switch.py", line 54, in async_turn_off
    await self.coordinator.api.async_set_title("foo")
AttributeError: 'BlueprintDataUpdateCoordinator' object has no attribute 'api'
```

**Comment by dknowles2** [comment]
Yes the integration is not ready for use yet. Most of the code is still just copied from the template. 

I'm hoping to have a basic working version in the next week or two.

**Comment by rossman-home** [comment]
> Yes the integration is not ready for use yet. Most of the code is still just copied from the template.
> 
> I'm hoping to have a basic working version in the next week or two.

Copy.  I was just looking around and seen the integration and got exited and wanted to try it.  Let me know if I can help with anything, I have a very basic understanding of HA, but I can test for you if needed.  Thanks for looking into this!

**Comment by dknowles2** [comment]
Okay, I pushed a proper release with basic implementation. It's still missing some features and I haven't tested everything yet, but feel free to give it a try. Any feedback (including things that are flat-out broken) is welcome!

(You should also be able to install via HACS as a custom repo)
