### ISSUE TITLE
It looks like this is Bluetooth only? Any chance of using Wifi?

### ISSUE THREAD

**Issue by rsabol77** [dknowles2/ha-pitboss#40]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I do not use bluetooth and grill is too far to reach it. 

### Describe the solution you'd like

Using WiFi would be a great addition. 

### Describe alternatives you've considered

None known

### Additional context

NA

**Comment by savdagod** [comment]
Does the wifi work for you in the app? Mine has terrible range, even when connecting to Bluetooth and my phone is literally touching the front of the controller (only 1-2 bars when doing that which is baffling). I’m in the process of getting a replacement controller to see if they’re all garbage or I got a dud.

**Comment by rsabol77** [comment]
> Does the wifi work for you in the app? Mine has terrible range, even when connecting to Bluetooth and my phone is literally touching the front of the controller (only 1-2 bars when doing that which is baffling). I’m in the process of getting a replacement controller to see if they’re all garbage or I got a dud.

WiFi works great. Haven’t tried to leave the house but I can say anywhere in the house or garage I have no issues. For S&Gs I just turned off WiFi and Bluetooth and everything still seems to be working.

**Comment by dknowles2** [comment]
This is Bluetooth only. If you don't have a Bluetooth receiver within range, I'd suggest looking at [ESPHome's bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html) feature which integrates natively with Home Assistant.
