### ISSUE TITLE
Pitboss Requirements not found

### ISSUE THREAD

**Issue by datagen24** [dknowles2/ha-pitboss#46]
## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 23, 2024 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-4.ui.nabu.casa
certificate_status | ready
instance_id | 024f2a183fca415aae14cd19ae7fee09
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 458.4 GB
disk_used | 86.3 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), ESPHome (2024.2.2), Silicon Labs Multiprotocol (2.4.4), OpenThread Border Router (2.5.0), Studio Code Server (5.15.0), Grafana (9.1.3), InfluxDB (5.0.0), Prometheus (1.0.0-beta.0), Node-RED (17.0.7), Network UPS Tools (0.13.0), Log Viewer (0.17.0), openWakeWord (1.10.0), Scrypted (18-jammy-full.s6-v0.93.0), Matter Server (5.4.1), File editor (5.8.0), chrony (3.0.1), Mosquitto broker (6.4.0), Grocy (0.21.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 4
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 29, 2024 at 4:48 PM
-- | --
current_recorder_run | March 9, 2024 at 2:06 AM
estimated_db_size | 1194.11 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

With most recent version I get error an error about the requirements not being met

Logger: homeassistant.setup
Source: setup.py:266
First occurred: March 9, 2024 at 2:08:50 AM (1 occurrences)
Last logged: March 9, 2024 at 2:08:50 AM

Setup failed for custom integration 'pitboss': Requirements for pitboss not found: ['pytboss==2024.2.1'].

### Reproduction steps

1. Install 2024.2.1 release

### Debug logs

```text
Logger: homeassistant.setup
Source: setup.py:266
First occurred: March 9, 2024 at 2:08:50 AM (1 occurrences)
Last logged: March 9, 2024 at 2:08:50 AM

Setup failed for custom integration 'pitboss': Requirements for pitboss not found: ['pytboss==2024.2.1'].
```

**Comment by dknowles2** [comment]
This sounds like #42
