### ISSUE TITLE
Deprecation warning (`async_add_job`) 

### ISSUE THREAD

**Issue by TTLucian** [dknowles2/ha-pitboss#47]
### System Health details

Deprecation warning: `async_add_job`

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

-

### Reproduction steps

Not applicable

### Debug logs

```text
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:188
First occurred: 20:05:57 (1 occurrences)
Last logged: 20:05:57

Detected that custom integration 'pitboss' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/pitboss/coordinator.py, line 70: self.hass.async_add_job(self.reset_device, device), please create a bug report at https://github.com/dknowles2/ha-pitboss/issues
```
```


### Diagnostics dump

_No response_

**Comment by dknowles2** [comment]
Thanks for the notice! 👍🏻
