### ISSUE TITLE
Sensor not marked unavailable

### ISSUE THREAD

**Issue by SomeFixItDude** [dknowles2/ha-pitboss#50]
## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.25-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4971
Installed Version | 1.34.0
Stage | running
Available Repositories | 1467
Downloaded Repositories | 8
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 116.7 GB
disk_used | 9.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Matter Server (5.6.0), Z-Wave JS (0.5.0), ESPHome (2024.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 1, 2024 at 1:17 PM
-- | --
current_recorder_run | May 6, 2024 at 3:54 PM
estimated_db_size | 147.16 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/dknowles2/ha-pitboss/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After unplugging my pitboss grill the sensors do not go to unavailable.  Maybe adding something like expire after setting to each sensor?

### Reproduction steps

1. Power on grill, with temp probe connected.
2. unplug grill
3. Sensors still at last values for grill even though not powered on and meat probe

### Debug logs

```text
I will pull if needed, think the issue is pretty self explanatory and reproducible
```

**Comment by dknowles2** [comment]
I just cut a 2024.5.0 release. Give that a try and let me know if it doesn't work. I probably won't have time to test it out this weekend on my own grill.
